//! Custom bulk-action routing.
//!
//! Bulk actions are registered on the [`ActixAdminBuilder`] via
//! [`add_bulk_action_for_entity`]; the handler is a plain closure that
//! receives the current DB connection, the list of selected ids and the
//! tenant reference (if any), and returns a human-readable message shown
//! as a flash notification on the redirected list page.
//!
//! Wire-up:
//! * The list page's actions dropdown renders one entry per registered
//!   bulk action.
//! * On click, the ids from the table's checkbox form are POSTed to
//!   `/{entity}/action/{name}` with the CSRF token attached.
//! * The route handler dispatches to the registered closure via
//!   `Entity::run_bulk_action` (generated by the derive macro).
//!
//! [`add_bulk_action_for_entity`]: crate::builder::ActixAdminBuilderTrait::add_bulk_action_for_entity

use actix_session::Session;
use actix_web::{http::header, web, Error, HttpRequest, HttpResponse};
use sea_orm::DatabaseConnection;

use crate::admin_prelude;
use crate::prelude::*;

use super::RoutePrelude;

/// Dispatch trait implemented per entity to route named bulk actions to
/// their concrete handlers. Add a manual `impl` to your entity:
///
/// ```ignore
/// #[actix_admin::prelude::async_trait(?Send)]
/// impl actix_admin::routes::ActixAdminBulkActionDispatch for post::Entity {
///     async fn run_bulk_action(
///         name: &str,
///         db: &sea_orm::DatabaseConnection,
///         ids: Vec<Self::Id>,
///         tenant_ref: Option<i32>,
///     ) -> Result<Option<String>, ActixAdminError> {
///         match name {
///             "mark_reviewed" => Ok(Some(format!("reviewed {}", ids.len()))),
///             _ => Ok(None),
///         }
///     }
/// }
/// ```
#[async_trait::async_trait(?Send)]
pub trait ActixAdminBulkActionDispatch: ActixAdminViewModelTrait {
    /// Execute the bulk action named `name` against `ids`. Returning
    /// `Ok(None)` means "no such action registered for this entity".
    async fn run_bulk_action(
        _name: &str,
        _db: &DatabaseConnection,
        _ids: Vec<Self::Id>,
        _tenant_ref: Option<i32>,
    ) -> Result<Option<String>, ActixAdminError> {
        Ok(None)
    }
}

/// HTTP handler for `POST /{entity}/action/{name}`.
pub async fn bulk_action<E: ActixAdminBulkActionDispatch + 'static>(
    session: Session,
    req: HttpRequest,
    data: web::Data<ActixAdmin>,
    db: web::Data<DatabaseConnection>,
    form: web::Form<Vec<(String, String)>>,
    path: web::Path<String>,
) -> Result<HttpResponse, Error> {
    let actix_admin = data.get_ref();
    let ctx = admin_prelude!(&session, &req, actix_admin, RoutePrelude::bulk(), E);

    let action_name = path.into_inner();
    if !ctx
        .view_model
        .bulk_actions
        .iter()
        .any(|a| a.name == action_name)
    {
        return Ok(HttpResponse::NotFound().body("unknown bulk action"));
    }

    let ids: Vec<E::Id> = form
        .iter()
        .filter_map(|(k, v)| (k == "ids").then(|| v.parse::<E::Id>().ok()).flatten())
        .collect();

    let db = db.get_ref();
    let result = E::run_bulk_action(&action_name, db, ids, ctx.tenant_ref).await;

    match result {
        Ok(Some(_msg)) => {
            // On success, bounce back to the entity's list page. We don't
            // yet have a flash-message channel; the message returned by the
            // handler is logged for observability.
            log::info!(target: "actix_admin::bulk_action", "{}/{action_name}: {_msg}", ctx.entity_name);
            Ok(HttpResponse::SeeOther()
                .append_header((
                    header::LOCATION,
                    format!(
                        "{}/{}/list",
                        actix_admin.configuration.base_path, ctx.entity_name
                    ),
                ))
                .finish())
        }
        Ok(None) => Ok(HttpResponse::NotFound().body("unknown bulk action")),
        Err(e) => Err(e.into()),
    }
}
