name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-geckodriver@latest
    - uses: browser-actions/setup-firefox@latest
    - name: Build
      run: cargo build --verbose
    - name: Run tests with bulma_css feature
      run: cargo test --verbose --features bulma_css --no-default-features
    - name: Run tests with bootstrapv5_css feature
      run: cargo test --verbose --features bootstrapv5_css --no-default-features
